[package]
name = "pluma"
version = "0.1.0"
license = "MIT"
authors = ["Reid Mitchell <reidmitchell1@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.13"
clap = "3.0.0-beta.1"
pluma_compiler = { path = "../compiler" }
