[package]
name = "pluma_repl"
version = "0.1.0"
authors = ["Reid Mitchell <reidmitchell1@gmail.com>"]
edition = "2018"

[dependencies]
pluma_compiler = { path = "../pluma_compiler" }
rustyline = "6.2.0"